//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenSoftware.RestraurantChicken.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantChickenEntities : DbContext
    {
        public RestaurantChickenEntities()
            : base("name=RestaurantChickenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NonRestaurant> NonRestaurants { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
    }
}
