//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenSoftware.RestraurantChicken.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Id { get; set; }
        public string InspectionID { get; set; }
        public string InspectorID { get; set; }
        public string EstablishmentID { get; set; }
        public string EstablishmentName { get; set; }
        public string EstablishmentAddress { get; set; }
        public string EstablishmentCity { get; set; }
        public string EstablishmnetZipCode { get; set; }
        public Nullable<double> EstablishmentLat { get; set; }
        public Nullable<double> EstablishmentLong { get; set; }
        public string EstablishmentTypeDesc { get; set; }
        public Nullable<double> InspectionScore { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<int> Core { get; set; }
        public Nullable<int> Non_Critical { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Priority_Foundation { get; set; }
    }
}
